In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('/Users/felixhermes/code/miguelferreira13/wildfire_prediction/wildfire_prediction/data/merged_file.csv')
data.head()

,Unnamed: 0,Date_x,Region,count()[unit: km^2],max() Precipitation,max() RelativeHumidity,max() SoilWaterContent,max() SolarRadiation,max() Temperature,max() WindSpeed,...,Bare / sparse vegetation,Permanent water bodies,Herbaceous wetland,"Closed forest, evergreen, broad leaf","Closed forest, deciduous broad leaf","Closed forest, unknown","Open forest, evergreen broad leaf","Open forest, deciduous broad leaf","Open forest, unknown definitions",Open sea
0,0,2005-01-01,NSW,8.002343e+05,1.836935,80.522964,0.414305,32.169781,35.878704,7.670482,...,0.2,0.2,0.1,14.7,6.8,0.3,0.5,3.7,10.3,0.1
1,1,2005-01-01,NT,1.357561e+06,315.266815,95.683342,0.496140,31.634459,38.136787,9.704402,...,0.4,0.1,0.1,1.0,7.7,0.1,0.1,13.6,9.3,0.5
2,2,2005-01-01,QL,1.730605e+06,74.452164,95.898270,0.472416,31.982830,37.047943,7.675632,...,1.1,0.1,0.0,5.3,13.3,0.3,0.1,12.0,11.0,0.3
3,3,2005-01-01,SA,9.913151e+05,3.193624,81.980751,0.263911,31.734528,38.326847,10.044715,...,4.8,1.2,0.1,0.3,1.3,0.1,0.1,1.4,5.3,0.6
4,4,2005-01-01,TA,6.778526e+04,13.604791,81.501442,0.368189,33.225517,16.228510,11.432408,...,0.1,1.9,1.4,50.1,0.6,1.1,7.2,1.5,7.2,3.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40971 entries, 0 to 40970
Data columns (total 50 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Unnamed: 0                                                40971 non-null  int64
 1   Date_x                                                    40971 non-null  object
 2   Region                                                    40971 non-null  object
 3   count()[unit: km^2]                                       40971 non-null  float64
 4   max() Precipitation                                       40964 non-null  float64
 5   max() RelativeHumidity                                    40929 non-null  float64
 6   max() SoilWaterContent                                    40971 non-null  float64
 7   max() SolarRadiation                                      40957 non-null  float64
 8   max() Temperature                                         40957 non-null  float64
 9   max() WindSpeed                                           40943 non-null  float64
 10  mean() Precipitation                                      40964 non-null  float64
 11  mean() RelativeHumidity                                   40929 non-null  float64
 12  mean() SoilWaterContent                                   40971 non-null  float64
 13  mean() SolarRadiation                                     40957 non-null  float64
 14  mean() Temperature                                        40957 non-null  float64
 15  mean() WindSpeed                                          40943 non-null  float64
 16  min() Precipitation                                       40964 non-null  float64
 17  min() RelativeHumidity                                    40929 non-null  float64
 18  min() SoilWaterContent                                    40971 non-null  float64
 19  min() SolarRadiation                                      40957 non-null  float64
 20  min() Temperature                                         40957 non-null  float64
 21  min() WindSpeed                                           40943 non-null  float64
 22  variance() Precipitation                                  40964 non-null  float64
 23  variance() RelativeHumidity                               40929 non-null  float64
 24  variance() SoilWaterContent                               40971 non-null  float64
 25  variance() SolarRadiation                                 40957 non-null  float64
 26  variance() Temperature                                    40957 non-null  float64
 27  variance() WindSpeed                                      40943 non-null  float64
 28  Year                                                      40971 non-null  int64
 29  Month                                                     40971 non-null  int64
 30  Day                                                       40971 non-null  int64
 31  Estimated_fire_area                                       26667 non-null  float64
 32  Mean_estimated_fire_brightness                            26667 non-null  float64
 33  Mean_estimated_fire_radiative_power                       26667 non-null  float64
 34  Vegetation_index_mean                                     40908 non-null  float64
 35  Vegetation_index_variance                                 40908 non-null  float64
 36  Shrubs                                                    40971 non-null  float64
 37  Herbaceous vegetation                                     40971 non-null  float64
 38  Cultivated and managed vegetation/agriculture (cropland)  40971 non-null  float64
 39  Urban / built up                                          40971 non-null  float64
 40  Bare / sparse vegetation                                  40971 non-null  float64
 41  Permanent water bodies                                    40971 non-null  float64
 42  Herbaceous wetland                                        40971 non-null  float64
 43  Closed forest, evergreen, broad leaf                      40971 non-null  float64
 44  Closed forest, deciduous broad leaf                       40971 non-null  float64
 45  Closed forest, unknown                                    40971 non-null  float64
 46  Open forest, evergreen broad leaf                         40971 non-null  float64
 47  Open forest, deciduous broad leaf                         40971 non-null  float64
 48  Open forest, unknown definitions                          40971 non-null  float64
 49  Open sea                                                  40971 non-null  float64
dtypes: float64(44), int64(4), object(2)
memory usage: 15.6+ MB

In [4]:
data.drop(columns = ['Unnamed: 0', 'Date_x', 'Mean_estimated_fire_brightness', 'Mean_estimated_fire_radiative_power'], inplace = True)

In [5]:
data['Estimated_fire_area']

0              NaN
1         4.945000
2        38.831579
3              NaN
4              NaN
           ...
40966          NaN
40967          NaN
40968     1.430000
40969          NaN
40970     9.000000
Name: Estimated_fire_area, Length: 40971, dtype: float64

In [6]:
data['Estimated_fire_area'] = data['Estimated_fire_area'].fillna(0)

In [7]:
data['Estimated_fire_area']

0         0.000000
1         4.945000
2        38.831579
3         0.000000
4         0.000000
           ...
40966     0.000000
40967     0.000000
40968     1.430000
40969     0.000000
40970     9.000000
Name: Estimated_fire_area, Length: 40971, dtype: float64

In [8]:
data['target'] = (data['Estimated_fire_area'] > 0).astype(int)

In [9]:
data['target'].unique()

array([0, 1])

In [10]:
data.head()

,Region,count()[unit: km^2],max() Precipitation,max() RelativeHumidity,max() SoilWaterContent,max() SolarRadiation,max() Temperature,max() WindSpeed,mean() Precipitation,mean() RelativeHumidity,...,Permanent water bodies,Herbaceous wetland,"Closed forest, evergreen, broad leaf","Closed forest, deciduous broad leaf","Closed forest, unknown","Open forest, evergreen broad leaf","Open forest, deciduous broad leaf","Open forest, unknown definitions",Open sea,target
0,NSW,8.002343e+05,1.836935,80.522964,0.414305,32.169781,35.878704,7.670482,0.044274,36.355567,...,0.2,0.1,14.7,6.8,0.3,0.5,3.7,10.3,0.1,0
1,NT,1.357561e+06,315.266815,95.683342,0.496140,31.634459,38.136787,9.704402,9.884958,61.494675,...,0.1,0.1,1.0,7.7,0.1,0.1,13.6,9.3,0.5,1
2,QL,1.730605e+06,74.452164,95.898270,0.472416,31.982830,37.047943,7.675632,1.453053,47.959364,...,0.1,0.0,5.3,13.3,0.3,0.1,12.0,11.0,0.3,1
3,SA,9.913151e+05,3.193624,81.980751,0.263911,31.734528,38.326847,10.044715,0.059078,30.057683,...,1.2,0.1,0.3,1.3,0.1,0.1,1.4,5.3,0.6,0
4,TA,6.778526e+04,13.604791,81.501442,0.368189,33.225517,16.228510,11.432408,3.099497,65.086764,...,1.9,1.4,50.1,0.6,1.1,7.2,1.5,7.2,3.0,0

In [11]:
data['split'] = np.random.randn(data.shape[0], 1)

msk = np.random.rand(len(data)) <= 0.7

train = data[msk]
test = data[~msk]

In [12]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28617 entries, 2 to 40970
Data columns (total 48 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Region                                                    28617 non-null  object
 1   count()[unit: km^2]                                       28617 non-null  float64
 2   max() Precipitation                                       28611 non-null  float64
 3   max() RelativeHumidity                                    28590 non-null  float64
 4   max() SoilWaterContent                                    28617 non-null  float64
 5   max() SolarRadiation                                      28609 non-null  float64
 6   max() Temperature                                         28609 non-null  float64
 7   max() WindSpeed                                           28600 non-null  float64
 8   mean() Precipitation                                      28611 non-null  float64
 9   mean() RelativeHumidity                                   28590 non-null  float64
 10  mean() SoilWaterContent                                   28617 non-null  float64
 11  mean() SolarRadiation                                     28609 non-null  float64
 12  mean() Temperature                                        28609 non-null  float64
 13  mean() WindSpeed                                          28600 non-null  float64
 14  min() Precipitation                                       28611 non-null  float64
 15  min() RelativeHumidity                                    28590 non-null  float64
 16  min() SoilWaterContent                                    28617 non-null  float64
 17  min() SolarRadiation                                      28609 non-null  float64
 18  min() Temperature                                         28609 non-null  float64
 19  min() WindSpeed                                           28600 non-null  float64
 20  variance() Precipitation                                  28611 non-null  float64
 21  variance() RelativeHumidity                               28590 non-null  float64
 22  variance() SoilWaterContent                               28617 non-null  float64
 23  variance() SolarRadiation                                 28609 non-null  float64
 24  variance() Temperature                                    28609 non-null  float64
 25  variance() WindSpeed                                      28600 non-null  float64
 26  Year                                                      28617 non-null  int64
 27  Month                                                     28617 non-null  int64
 28  Day                                                       28617 non-null  int64
 29  Estimated_fire_area                                       28617 non-null  float64
 30  Vegetation_index_mean                                     28569 non-null  float64
 31  Vegetation_index_variance                                 28569 non-null  float64
 32  Shrubs                                                    28617 non-null  float64
 33  Herbaceous vegetation                                     28617 non-null  float64
 34  Cultivated and managed vegetation/agriculture (cropland)  28617 non-null  float64
 35  Urban / built up                                          28617 non-null  float64
 36  Bare / sparse vegetation                                  28617 non-null  float64
 37  Permanent water bodies                                    28617 non-null  float64
 38  Herbaceous wetland                                        28617 non-null  float64
 39  Closed forest, evergreen, broad leaf                      28617 non-null  float64
 40  Closed forest, deciduous broad leaf                       28617 non-null  float64
 41  Closed forest, unknown                                    28617 non-null  float64
 42  Open forest, evergreen broad leaf                         28617 non-null  float64
 43  Open forest, deciduous broad leaf                         28617 non-null  float64
 44  Open forest, unknown definitions                          28617 non-null  float64
 45  Open sea                                                  28617 non-null  float64
 46  target                                                    28617 non-null  int64
 47  split                                                     28617 non-null  float64
dtypes: float64(43), int64(4), object(1)
memory usage: 10.7+ MB

In [13]:
train.head()

,Region,count()[unit: km^2],max() Precipitation,max() RelativeHumidity,max() SoilWaterContent,max() SolarRadiation,max() Temperature,max() WindSpeed,mean() Precipitation,mean() RelativeHumidity,...,Herbaceous wetland,"Closed forest, evergreen, broad leaf","Closed forest, deciduous broad leaf","Closed forest, unknown","Open forest, evergreen broad leaf","Open forest, deciduous broad leaf","Open forest, unknown definitions",Open sea,target,split
2,QL,1.730605e+06,74.452164,95.898270,0.472416,31.982830,37.047943,7.675632,1.453053,47.959364,...,0.0,5.3,13.3,0.3,0.1,12.0,11.0,0.3,1,1.270917
4,TA,6.778526e+04,13.604791,81.501442,0.368189,33.225517,16.228510,11.432408,3.099497,65.086764,...,1.4,50.1,0.6,1.1,7.2,1.5,7.2,3.0,0,-0.363123
5,VI,2.294532e+05,1.129023,80.269424,0.389527,30.274399,25.299295,9.830581,0.052024,56.456559,...,0.3,23.9,3.8,0.3,1.5,2.7,5.2,0.9,0,-0.046807
9,QL,1.730605e+06,87.775497,95.837463,0.477548,31.729107,35.675449,7.094274,1.544607,48.593844,...,0.0,5.3,13.3,0.3,0.1,12.0,11.0,0.3,1,0.337662
10,SA,9.913151e+05,3.230288,84.714577,0.263650,32.662922,35.849258,9.287691,0.352733,35.461572,...,0.1,0.3,1.3,0.1,0.1,1.4,5.3,0.6,0,0.538558

In [14]:
train.to_csv('/Users/felixhermes/code/miguelferreira13/wildfire_prediction/wildfire_prediction/data/FH_train.csv')
test.to_csv('/Users/felixhermes/code/miguelferreira13/wildfire_prediction/wildfire_prediction/data/FH_test.csv')
data.to_csv('/Users/felixhermes/code/miguelferreira13/wildfire_prediction/wildfire_prediction/data/FH_data.csv')