# Exploratory Analysis

In [124]:
import pandas as pd

In [125]:
df = pd.read_csv('../raw_data/Jan_16/HistoricalWeather.csv')

In [126]:
df.Parameter.value_counts()

SoilWaterContent    40971
Precipitation       40964
Temperature         40957
SolarRadiation      40957
WindSpeed           40943
RelativeHumidity    40929
Name: Parameter, dtype: int64

In [127]:
# df_wf[df_wf['Date']=='2014-01-01']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245721 entries, 0 to 245720
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Date                 245721 non-null  object
 1   Region               245721 non-null  object
 2   Parameter            245721 non-null  object
 3   count()[unit: km^2]  245721 non-null  float64
 4   min()                245721 non-null  float64
 5   max()                245721 non-null  float64
 6   mean()               245721 non-null  float64
 7   variance()           245721 non-null  float64
dtypes: float64(5), object(3)
memory usage: 15.0+ MB

In [128]:
pivot = df.pivot_table(['min()', 'max()', 'mean()', 'variance()'], ['Date','Region','count()[unit: km^2]'], 'Parameter')

In [129]:
pivot

                                              max()                   \
Parameter                             Precipitation RelativeHumidity
Date       Region count()[unit: km^2]
2005-01-01 NSW    8.002343e+05             1.836935        80.522964
           NT     1.357561e+06           315.266815        95.683342
           QL     1.730605e+06            74.452164        95.898270
           SA     9.913151e+05             3.193624        81.980751
           TA     6.778526e+04            13.604791        81.501442
...                                             ...              ...
2021-01-09 QL     1.730605e+06            76.539787        99.068840
           SA     9.913151e+05             0.011193        87.400673
           TA     6.778526e+04             0.671226        85.533943
           VI     2.294532e+05             0.056003        86.733360
           WA     2.528546e+06             3.487231        84.094559

                                                                       \
Parameter                             SoilWaterContent SolarRadiation
Date       Region count()[unit: km^2]
2005-01-01 NSW    8.002343e+05                0.414305      32.169781
           NT     1.357561e+06                0.496140      31.634459
           QL     1.730605e+06                0.472416      31.982830
           SA     9.913151e+05                0.263911      31.734528
           TA     6.778526e+04                0.368189      33.225517
...                                                ...            ...
2021-01-09 QL     1.730605e+06                0.491771      31.479033
           SA     9.913151e+05                0.291472      32.616680
           TA     6.778526e+04                0.335788      33.143166
           VI     2.294532e+05                0.411591      32.725616
           WA     2.528546e+06                0.374027      32.355438

                                                                    mean()  \
Parameter                             Temperature  WindSpeed Precipitation
Date       Region count()[unit: km^2]
2005-01-01 NSW    8.002343e+05          35.878704   7.670482      0.044274
           NT     1.357561e+06          38.136787   9.704402      9.884958
           QL     1.730605e+06          37.047943   7.675632      1.453053
           SA     9.913151e+05          38.326847  10.044715      0.059078
           TA     6.778526e+04          16.228510  11.432408      3.099497
...                                           ...        ...           ...
2021-01-09 QL     1.730605e+06          32.235790  12.415317      4.161668
           SA     9.913151e+05          31.718039   6.366586      0.000055
           TA     6.778526e+04          18.692577   8.090628      0.020243
           VI     2.294532e+05          29.507277   5.823341      0.001011
           WA     2.528546e+06          36.807751   9.305047      0.024427

                                                                         \
Parameter                             RelativeHumidity SoilWaterContent
Date       Region count()[unit: km^2]
2005-01-01 NSW    8.002343e+05               36.355567         0.170931
           NT     1.357561e+06               61.494675         0.167735
           QL     1.730605e+06               47.959364         0.185641
           SA     9.913151e+05               30.057683         0.056047
           TA     6.778526e+04               65.086764         0.211360
...                                                ...              ...
2021-01-09 QL     1.730605e+06               69.051520         0.267441
           SA     9.913151e+05               27.551116         0.060072
           TA     6.778526e+04               68.691791         0.225610
           VI     2.294532e+05               52.351424         0.221117
           WA     2.528546e+06               25.539865         0.052128

                                                      ...            min()  \
Parameter                             SolarRadiation  ... SoilWaterContent
Date       Region count()[unit: km^2]                 ...
2005-01-01 NSW    8.002343e+05             26.749389  ...         0.002245
           NT     1.357561e+06             19.781791  ...         0.000000
           QL     1.730605e+06             27.056979  ...         0.000000
           SA     9.913151e+05             27.142643  ...         0.000000
           TA     6.778526e+04             26.755711  ...         0.000000
...                                              ...  ...              ...
2021-01-09 QL     1.730605e+06             19.840769  ...         0.000000
           SA     9.913151e+05             31.117618  ...         0.000000
           TA     6.778526e+04             31.766111  ...         0.000000
           VI     2.294532e+05             32.108984  ...         0.000000
           WA     2.528546e+06             29.266381  ...         0.000000

                                                                            \
Parameter                             SolarRadiation Temperature WindSpeed
Date       Region count()[unit: km^2]
2005-01-01 NSW    8.002343e+05             14.515009   14.485785  1.354448
           NT     1.357561e+06              2.518120   24.179960  1.840394
           QL     1.730605e+06              6.033827   20.951620  1.106028
           SA     9.913151e+05             17.861103   14.095855  2.023657
           TA     6.778526e+04             20.742302    6.686816  1.995647
...                                              ...         ...       ...
2021-01-09 QL     1.730605e+06              3.746360   16.670816  0.695189
           SA     9.913151e+05             16.663145   16.530344  1.988944
           TA     6.778526e+04             26.500408   14.016933  1.216655
           VI     2.294532e+05             29.201761   16.691036  0.997281
           WA     2.528546e+06             18.421680   20.764585  1.316897

                                         variance()                   \
Parameter                             Precipitation RelativeHumidity
Date       Region count()[unit: km^2]
2005-01-01 NSW    8.002343e+05         2.836210e-02       253.559937
           NT     1.357561e+06         5.460593e+02       584.201131
           QL     1.730605e+06         3.564126e+01       403.134377
           SA     9.913151e+05         4.283741e-02       246.044713
           TA     6.778526e+04         1.206860e+01       111.754034
...                                             ...              ...
2021-01-09 QL     1.730605e+06         7.313473e+01       306.604594
           SA     9.913151e+05         3.104215e-07       118.103051
           TA     6.778526e+04         4.106938e-03        57.807329
           VI     2.294532e+05         2.120286e-05       326.879961
           WA     2.528546e+06         1.698659e-02       219.361327

                                                                       \
Parameter                             SoilWaterContent SolarRadiation
Date       Region count()[unit: km^2]
2005-01-01 NSW    8.002343e+05                0.007758       6.078587
           NT     1.357561e+06                0.026743      58.942658
           QL     1.730605e+06                0.012679      29.500832
           SA     9.913151e+05                0.001917       7.914246
           TA     6.778526e+04                0.007121      12.826400
...                                                ...            ...
2021-01-09 QL     1.730605e+06                0.016877      43.080371
           SA     9.913151e+05                0.001404       5.091990
           TA     6.778526e+04                0.007276       1.750340
           VI     2.294532e+05                0.006959       0.448802
           WA     2.528546e+06                0.001778       9.209243


Parameter                             Temperature WindSpeed
Date       Region count()[unit: km^2]
2005-01-01 NSW    8.002343e+05          18.562212  0.850048
           NT     1.357561e+06          12.920252  1.930014
           QL     1.730605e+06          13.792599  0.883048
           SA     9.913151e+05          34.799336  1.655908
           TA     6.778526e+04           4.912013  2.963118
...                                           ...       ...
2021-01-09 QL     1.730605e+06          13.246371  2.263192
           SA     9.913151e+05           4.555333  0.637816
           TA     6.778526e+04           1.888476  0.939796
           VI     2.294532e+05          11.969675  0.399062
           WA     2.528546e+06           6.610068  0.879385

[40971 rows x 24 columns]

In [130]:
pivot.columns = [' '.join(col).strip() for col in pivot.columns.values]

In [131]:
pivot.columns

Index(['max() Precipitation', 'max() RelativeHumidity',
       'max() SoilWaterContent', 'max() SolarRadiation', 'max() Temperature',
       'max() WindSpeed', 'mean() Precipitation', 'mean() RelativeHumidity',
       'mean() SoilWaterContent', 'mean() SolarRadiation',
       'mean() Temperature', 'mean() WindSpeed', 'min() Precipitation',
       'min() RelativeHumidity', 'min() SoilWaterContent',
       'min() SolarRadiation', 'min() Temperature', 'min() WindSpeed',
       'variance() Precipitation', 'variance() RelativeHumidity',
       'variance() SoilWaterContent', 'variance() SolarRadiation',
       'variance() Temperature', 'variance() WindSpeed'],
      dtype='object')

In [132]:
pivot = pivot.reset_index()

In [133]:
pivot.isna().sum()

Date                            0
Region                          0
count()[unit: km^2]             0
max() Precipitation             7
max() RelativeHumidity         42
max() SoilWaterContent          0
max() SolarRadiation           14
max() Temperature              14
max() WindSpeed                28
mean() Precipitation            7
mean() RelativeHumidity        42
mean() SoilWaterContent         0
mean() SolarRadiation          14
mean() Temperature             14
mean() WindSpeed               28
min() Precipitation             7
min() RelativeHumidity         42
min() SoilWaterContent          0
min() SolarRadiation           14
min() Temperature              14
min() WindSpeed                28
variance() Precipitation        7
variance() RelativeHumidity    42
variance() SoilWaterContent     0
variance() SolarRadiation      14
variance() Temperature         14
variance() WindSpeed           28
dtype: int64

In [138]:
pivot[["Year", "Month", "Day"]] = pivot["Date"].str.split("-", expand = True)

In [140]:
pivot['Date'] = pd.to_datetime(pivot['Date'])

In [143]:
pivot.to_csv('../wildfire_prediction/data/weather.csv')